apiVersion: batch/v1
kind: Job
metadata:
  name: superset-init-db
  namespace: apache-test
  uid: 0917c3c0-993d-48d7-b2b1-f90eb3570d89
  resourceVersion: '788971'
  generation: 1
  creationTimestamp: '2023-04-28T16:23:56Z'
  labels:
    controller-uid: 0917c3c0-993d-48d7-b2b1-f90eb3570d89
    job-name: superset-init-db
  annotations:
    batch.kubernetes.io/job-tracking: ''
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
status:
  conditions:
    - type: Complete
      status: 'True'
      lastProbeTime: '2023-04-28T16:25:33Z'
      lastTransitionTime: '2023-04-28T16:25:33Z'
  startTime: '2023-04-28T16:23:56Z'
  completionTime: '2023-04-28T16:25:33Z'
  succeeded: 1
  uncountedTerminatedPods: {}
  ready: 0
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 6
  template:
    metadata:
      name: superset-init-db
      labels:
        job-name: superset-init-db
    spec:
      volumes:
        - name: superset-config
          secret:
            secretName: superset-config
            defaultMode: 420
      initContainers:
        - name: wait-for-postgres
          image: jwilder/dockerize:latest
          command:
            - /bin/sh
            - '-c'
            - dockerize -wait "tcp://$DB_HOST:$DB_PORT" -timeout 120s
          envFrom:
            - secretRef:
                name: superset-env
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      containers:
        - name: superset-init-db
          image: apache/superset:2.1.0
          command:
            - /bin/sh
            - '-c'
            - >-
              . /app/pythonpath/superset_bootstrap.sh; .
              /app/pythonpath/superset_init.sh
          envFrom:
            - secretRef:
                name: superset-env
          resources: {}
          volumeMounts:
            - name: superset-config
              readOnly: true
              mountPath: /app/pythonpath
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        runAsUser: 0
      schedulerName: default-scheduler
  completionMode: NonIndexed
  suspend: false