apiVersion: batch/v1
kind: Job
metadata:
  name: superset-init-db
  labels:
    controller-uid: 4d45069a-abf8-48c7-8438-a399106f2740
    job-name: superset-init-db
  annotations:
    batch.kubernetes.io/job-tracking: ''
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  selfLink: /apis/batch/v1/namespaces/apache-superset/jobs/superset-init-db
status:
  conditions:
    - type: Complete
      status: 'True'
      lastProbeTime: '2023-04-28T13:50:40Z'
      lastTransitionTime: '2023-04-28T13:50:40Z'
  startTime: '2023-04-28T13:48:56Z'
  completionTime: '2023-04-28T13:50:40Z'
  succeeded: 1
  uncountedTerminatedPods: {}
  ready: 0
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 6
  selector:
    matchLabels:
      controller-uid: 4d45069a-abf8-48c7-8438-a399106f2740
  template:
    metadata:
      name: superset-init-db
      labels:
        controller-uid: 4d45069a-abf8-48c7-8438-a399106f2740
        job-name: superset-init-db
    spec:
      volumes:
        - name: superset-config
          secret:
            secretName: superset-config
            defaultMode: 420
      initContainers:
        - name: wait-for-postgres
          image: jwilder/dockerize:latest
          command:
            - /bin/sh
            - '-c'
            - dockerize -wait "tcp://$DB_HOST:$DB_PORT" -timeout 120s
          envFrom:
            - secretRef:
                name: superset-env
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      containers:
        - name: superset-init-db
          image: apache/superset:2.1.0
          command:
            - /bin/sh
            - '-c'
            - >-
              . /app/pythonpath/superset_bootstrap.sh; .
              /app/pythonpath/superset_init.sh
          envFrom:
            - secretRef:
                name: superset-env
          resources: {}
          volumeMounts:
            - name: superset-config
              readOnly: true
              mountPath: /app/pythonpath
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        runAsUser: 0
      schedulerName: default-scheduler
  completionMode: NonIndexed
  suspend: false
