apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: do-block-storage
  labels:
    c3.doks.digitalocean.com/component: csi-controller-service
    c3.doks.digitalocean.com/plane: data
    doks.digitalocean.com/managed: 'true'
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
allowVolumeExpansion: true
provisioner: dobs.csi.digitalocean.com
reclaimPolicy: Delete
volumeBindingMode: Immediate