apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-superset-postgresql-0
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: superset
    app.kubernetes.io/name: postgresql
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com
    volume.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com
  finalizers:
    - kubernetes.io/pvc-protection
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: pvc-1
  storageClassName: do-block-storage
  volumeMode: Filesystem
