apiVersion: v1
kind: ConfigMap
metadata:
  name: superset-redis-scripts
  namespace: apache-superset
  labels:
    app.kubernetes.io/instance: superset
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-17.9.4
  annotations:
    meta.helm.sh/release-name: superset
    meta.helm.sh/release-namespace: apache-superset
  selfLink: /api/v1/namespaces/apache-superset/configmaps/superset-redis-scripts
data:
  start-master.sh: >
    #!/bin/bash


    [[ -f $REDIS_PASSWORD_FILE ]] && export REDIS_PASSWORD="$(<
    "${REDIS_PASSWORD_FILE}")"

    if [[ -f /opt/bitnami/redis/mounted-etc/master.conf ]];then
        cp /opt/bitnami/redis/mounted-etc/master.conf /opt/bitnami/redis/etc/master.conf
    fi

    if [[ -f /opt/bitnami/redis/mounted-etc/redis.conf ]];then
        cp /opt/bitnami/redis/mounted-etc/redis.conf /opt/bitnami/redis/etc/redis.conf
    fi

    ARGS=("--port" "${REDIS_PORT}")

    ARGS+=("--protected-mode" "no")

    ARGS+=("--include" "/opt/bitnami/redis/etc/redis.conf")

    ARGS+=("--include" "/opt/bitnami/redis/etc/master.conf")

    exec redis-server "${ARGS[@]}"
binaryData: {}
